[platformio]
default_envs = heltec_s3_devkit

[env:heltec_s3_devkit]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_F8:5B:1B:BF:02:A8-if00

upload_speed = 921600
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_F8:5B:1B:BF:02:A8-if00

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  +<*>
  -<apps/listener/*>

lib_deps =
  adafruit/Adafruit NeoPixel
  pololu/VL53L1X
  jgromes/RadioLib @ ^7.7.1


[env:heltec_v4_listener]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_A4:CB:8F:A6:78:F4-if00

upload_speed = 921600
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_A4:CB:8F:A6:78:F4-if00

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  -<*>
  +<apps/listener/main.cpp>
  +<fw_radio_profile.cpp>
  +<fw_radio_channel.cpp>
  +<fw_packet.cpp>

lib_deps =
  jgromes/RadioLib @ ^7.7.1
